Django-Apps/mysite1/food/urls.py
from django.urls import path

from . import views

app_name = "food"
urlpatterns = [
    path("", views.IndexClassView.as_view(), name="index"),
    path("<int:pk>/", views.FoodDetail.as_view(), name="detail"),
    path("add", views.CreateItem.as_view(), name="create_item"),
    path("update/<int:id>/", views.update_item, name="update_item"),
    path("delete/<int:id>/", views.delete_item, name="delete_item"),
]

Django-Apps/mysite1/mysite1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as authentication_views
from django.urls import include, path
from users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/", include("food.urls")),
    path("register/", user_views.register, name="register"),
    path(
        "login/",
        authentication_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        authentication_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("profile/", user_views.profilepage, name="profile"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# urlpatterns += [
#     # ... the rest of your URLconf goes here ...
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Django-Apps/mysite1/food/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(
        max_length=500,
        default="https://p.kindpng.com/picc/s/79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.png",
    )

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

Django-Apps/mysite1/users/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profilepic.jpg", upload_to="profile_pictures")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

Django-Apps/mysite1/food/forms.py
from django import forms

from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name", "item_desc", "item_price", "item_image"]

Django-Apps/mysite1/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

Django-Apps/mysite1/food/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from .forms import ItemForm
from .models import Item

# Create your views here.

# def index(request):
#     item_list = Item.objects.all()
#     context= {
#         'item_list': item_list,
#     }
#     return render(request, 'food/index.html', context)


class IndexClassView(ListView):
    model = Item
    template_name = "food/index.html"
    context_object_name = "item_list"


# def detail(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item': item,
#     }
#     return render(request, 'food/detail.html', context)


class FoodDetail(DetailView):
    model = Item
    template_name = "food/detail.html"


# def create_item(request):
#     form = ItemForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
#     return render(request, 'food/item-form.html', {'form':form})


class CreateItem(LoginRequiredMixin, CreateView):
    model = Item
    fields = ["item_name", "item_desc", "item_price", "item_image"]
    template_name = "food/item-form.html"

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect("food:index")
    return render(request, "food/item-form.html", {"form": form, "item": item})


def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == "POST":
        item.delete()
        return redirect("food:index")
    return render(request, "food/item-delete.html", {"item": item})

Django-Apps/mysite1/users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import RegisterForm

# Create your views here.


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Welcome {username}, your account is created")
            return redirect("login")
    else:
        form = RegisterForm()
    return render(request, "users/register.html", {"form": form})


@login_required
def profilepage(request):
    return render(request, "users/profile.html")

Django-Apps/mysite1/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script></head>

    <title>Document</title>
</head>
<body>

        <nav class="navbar navbar-dark bg-dark">
                <a href="{% url 'food:index' %}" class="navbar-brand">FoodApp</a>

                <div class="navbar">
                    <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                     <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    {% endif %}

                </div>
            </nav>
          {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                    {{ message }}
            </div>

            {% endfor %}
          {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

Django-Apps/mysite1/food/templates/food/detail.html
{% extends 'food/base.html' %}


{% block body %}
</br>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{ item.item_image }}" class="card"/>
        </div>

        <div class="col-md-6">
           <h1>{{ object.item_name }}</h1>
<h2>{{ object.item_desc }}</h2>
<h3>${{ object.item_price }}</h3>
        <a href="{% url 'food:delete_item' item.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

Django-Apps/mysite1/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FoodApp</title>
   <body>
{% block body %}
</br>
{% for item in item_list %}
<div class="row">
    <div class="col-mid-3 offset-md-2">
<img class="card" height="150px" src="{{ item.item_image }}">
    </div>
    <div class="col-md-4">
        <h3>{{ item.item_name }}</h3>
        <h5>{{ item.item_desc }}</h5>
        <h5>${{ item.item_price }}</h5>
        <h6>{{ item.user_name }}</h6>

    </div>
    <div class="col-md-2">
        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>

    </div>
</div>

{% endfor %}
{% endblock %}

</body>
</html>

Django-Apps/mysite1/food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container" align="center">
            <form method="POST">
    {% csrf_token %}
    </br>
    <h2 >Are you sure you want to delete {{ item.item_name }}?</h2>
    </br>
    <button type="submit" class="btn btn-warning">Confirm</button>
</form>
    </div>

{% endblock %}

Django-Apps/mysite1/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
</br>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Save</button>
</form>
{% endblock %}

Django-Apps/mysite1/users/templates/users/login.html
{% extends 'food/base.html' %}
{% block body %}
</br>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

Django-Apps/mysite1/users/templates/users/logout.html
{% extends 'food/base.html' %}
{% block body %}
</br>
<h1>You have been logged out</h1>
{% endblock %}

Django-Apps/mysite1/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}">

Django-Apps/mysite1/users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body %}
</br>
<form method="POST">
  <table>
  {% csrf_token %}
  {{ form.as_table }}
  </table>
  <button type="submit">Sign up</button>
</form>
{% endblock %}